# Generated by Django 4.0.3 on 2022-03-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Способ решения')),
            ],
            options={
                'verbose_name': 'Способ решения',
                'verbose_name_plural': 'Способы решений',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_task', models.CharField(default=28, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('preview_image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('video_url', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ege_task.category')),
            ],
            options={
                'verbose_name': 'Разбор задачи',
                'verbose_name_plural': 'Разборы задач',
                'ordering': ['time_create', 'number_task'],
            },
        ),
    ]
